services:
  rails:
    build: .
    image: ror_ssr_hmr:1.0.0
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    ports:
      - 3000:3000
      - 3035:3035

volumes:
  node_modules:
