name: Ruby specs

on: [push, pull_request]

jobs:
  test:
    name: Ruby specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Ruby specs
        run: bundle exec rspec
