name: Ruby specs

on: [pull_request]

jobs:
  test:
    name: Ruby specs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Ruby specs
        run: |
          bundle install
          yarn install
          ./bin/shakapacker
          bundle exec rspec
